### ISSUE TITLE
OSCP request being sent with an incorrect serial number.

### ISSUE THREAD

**Issue by amdrsantos** [strongswan/strongswan#1415] opened 2022-11-14 12:05 UTC
**System:**
 - OS: Debian10
 - Kernel version: 4.19.81
 - strongSwan version(s): 5.9.8
 - Tested/confirmed with the latest version: yes

**Describe the bug**
OSCP request is being sent with an incorrect serial number. The expected serial number is 9A, but the OCSP request in OCSP is shown as -66.

**To Reproduce**
Try to create a connection between two peers with certificate authorization, using OCSP 

**Expected behavior**
The OCSP request should be sent with serial number 9A and not -66

**Logs/Backtraces**
OSCP log:
```
OCSP Request Data:
    Version: 1 (0x0)
    Requestor List:
        Certificate ID:
          Hash Algorithm: sha1
          Issuer Name Hash: 9AD8160945F2429EF1F82BA6C4844EB5CCC99941
          Issuer Key Hash: 74B91076CF5A7251F976E5149E72112908252751
          Serial Number: -66
    Request Extensions:
        OCSP Nonce:
            041072A1FC7B54EB58AE647C82A780FC260A
        Acceptable OCSP Responses:
            Basic OCSP Response
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = AB, ST = CDE, L = VFR, O = BOB, OU = BOB, CN = CA
    Produced At: Nov 14 11:43:02 2022 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 9AD8160945F2429EF1F82BA6C4844EB5CCC99941
      Issuer Key Hash: 74B91076CF5A7251F976E5149E72112908252751
      Serial Number: -66
    Cert Status: unknown
    This Update: Nov 14 11:43:02 2022 GMT
```
Which causes the authentication to fail:
```
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[IKE] received end entity cert "C=AB, ST=CDE, O=ASD, OU=ASD, CN=ASD, E=bb3@bb.com"
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG]   using certificate "C=AB, ST=CDE, O=ASD, OU=ASD, CN=ASD, E=bb3@bb.com"
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG]   using trusted ca certificate "C=AB, ST=CDE, L=VFR, O=BOB, OU=BOB, CN=CA"
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG]   reached self-signed root ca with a path length of 0
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG] checking certificate status of "C=AB, ST=CDE, O=ASD, OU=ASD, CN=ASD, E=bb3@bb.com"
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG]   requesting ocsp status from 'http://10.0.2.5:8101' ...
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG]   ocsp response correctly signed by "C=AB, ST=CDE, L=VFR, O=BOB, OU=BOB, CN=CA"
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG]   ocsp response contains no status on our certificate
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG] ocsp check failed, fallback to crl
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG] certificate status is not available
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[IKE] authentication of 'C=AB, ST=CDE, O=ASD, OU=ASD, CN=ASD, E=bb3@bb.com' with RSA_EMSA_PKCS1_SHA2_384 successful
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG] constraint check failed: RULE_CRL_VALIDATION is FAILED, but requires at least SKIPPED
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG] selected peer config 'GX1' unacceptable: constraint checking failed
Nov 14 11:43:02 xmm4-1-1 charon[14690]: 14[CFG] no alternative config found
```

The certificate is seen from the peer's strongSwan seems ok:
```
  subject:  "C=AB, ST=CDE, O=ASD, OU=ASD, CN=ASD, E=bb3@bb.com"
  issuer:   "C=AB, ST=CDE, L=VFR, O=BOB, OU=BOB, CN=CA"
  validity:  not before Nov 11 12:36:26 2022, ok
             not after  Nov 11 12:36:26 2023, ok (expires in 362 days)
  serial:    9a
  altNames:  ASD, 10.100.210.171, 10.100.210.194, 10.220.193.48, 10.220.193.50, 2001::171, 2002::10, 10.220.192.203, 2001::203, 10.220.196.196, 2001::196, 10.220.16.146, 10.220.16.150, 10.220.169.210, 10.220.196.196
  flags:     serverAuth clientAuth
  authkeyId: 74:b9:10:76:cf:5a:72:51:f9:76:e5:14:9e:72:11:29:08:25:27:51
  subjkeyId: 22:64:e3:4e:46:70:1f:ce:b0:37:d1:b2:c4:73:c4:c4:49:07:5d:94
  pubkey:    RSA 4096 bits, has private key
  keyid:     86:d9:42:ca:7c:99:9c:04:bf:e2:af:34:9e:3e:b4:5a:a8:4e:1b:dc
  subjkey:   22:64:e3:4e:46:70:1f:ce:b0:37:d1:b2:c4:73:c4:c4:49:07:5d:94
```
And in the local strongSwan as well:
```
List of X.509 End Entity Certificates

  subject:  "C=AB, ST=CDE, O=ASD, OU=ASD, CN=ASD, E=bb4@bb.com"
  issuer:   "C=AB, ST=CDE, L=VFR, O=BOB, OU=BOB, CN=CA"
  validity:  not before Nov 11 12:55:11 2022, ok
             not after  Nov 11 12:55:11 2023, ok (expires in 362 days)
  serial:    9b
  altNames:  10.100.210.171, 10.100.210.194, 10.220.193.48, 10.220.193.50, 2001::171, 2002::10, 10.220.192.203, 2001::203, 10.220.196.196, 2001::196, 10.220.16.146, 10.220.16.150, 10.220.169.210, 10.220.196.196
  flags:     serverAuth clientAuth
  authkeyId: 74:b9:10:76:cf:5a:72:51:f9:76:e5:14:9e:72:11:29:08:25:27:51
  subjkeyId: e6:c0:ef:75:58:1d:ae:d7:6b:26:75:79:c3:f4:e5:81:5e:57:78:e6
  pubkey:    RSA 4096 bits, has private key
  keyid:     86:7a:43:90:52:33:87:07:8c:e3:9f:ce:af:82:04:d6:fa:96:18:1f
  subjkey:   e6:c0:ef:75:58:1d:ae:d7:6b:26:75:79:c3:f4:e5:81:5e:57:78:e6

  subject:  "C=AB, ST=CDE, O=ASD, OU=ASD, CN=ASD, E=bb3@bb.com"
  issuer:   "C=AB, ST=CDE, L=VFR, O=BOB, OU=BOB, CN=CA"
  validity:  not before Nov 11 12:36:26 2022, ok
             not after  Nov 11 12:36:26 2023, ok (expires in 362 days)
  serial:    9a
  altNames:  ASD, 10.100.210.171, 10.100.210.194, 10.220.193.48, 10.220.193.50, 2001::171, 2002::10, 10.220.192.203, 2001::203, 10.220.196.196, 2001::196, 10.220.16.146, 10.220.16.150, 10.220.169.210, 10.220.196.196
  flags:     serverAuth clientAuth
  authkeyId: 74:b9:10:76:cf:5a:72:51:f9:76:e5:14:9e:72:11:29:08:25:27:51
  subjkeyId: 22:64:e3:4e:46:70:1f:ce:b0:37:d1:b2:c4:73:c4:c4:49:07:5d:94
  pubkey:    RSA 4096 bits
  keyid:     86:d9:42:ca:7c:99:9c:04:bf:e2:af:34:9e:3e:b4:5a:a8:4e:1b:dc
  subjkey:   22:64:e3:4e:46:70:1f:ce:b0:37:d1:b2:c4:73:c4:c4:49:07:5d:94

List of X.509 CA Certificates

  subject:  "C=AB, ST=CDE, L=VFR, O=BOB, OU=BOB, CN=CA"
  issuer:   "C=AB, ST=CDE, L=VFR, O=BOB, OU=BOB, CN=CA"
  validity:  not before Nov 10 18:28:53 2022, ok
             not after  Nov 07 18:28:53 2032, ok (expires in 3646 days)
  serial:    32:b8:9a:9c:28:24:00:b6:33:b4:72:a5:35:42:36:7b:2e:73:a3:04
  flags:     CA CRLSign self-signed
  authkeyId: 74:b9:10:76:cf:5a:72:51:f9:76:e5:14:9e:72:11:29:08:25:27:51
  subjkeyId: 74:b9:10:76:cf:5a:72:51:f9:76:e5:14:9e:72:11:29:08:25:27:51
  pubkey:    RSA 2048 bits
  keyid:     73:41:f1:c8:5b:5e:c9:a2:56:c1:03:21:4a:d7:9e:06:86:0d:55:01
  subjkey:   74:b9:10:76:cf:5a:72:51:f9:76:e5:14:9e:72:11:29:08:25:27:51

List of OCSP Responses

  issuer:   "C=AB, ST=CDE, L=VFR, O=BOB, OU=BOB, CN=CA"
  update:    this on Nov 14 11:43:02 2022, ok
             next on Nov 14 11:43:32 2022, expired (20 minutes ago)
  responses: 9a: unknown
```

**Additional context**
It seems that a sign expression has gone wrong: 9A -> FF9A -> -66
When the otherNames fields are removed from the X509 certificate, the request is being sent with correct serial number. Can this be an ASN.1 parser issue.

It is attached here the certificates and root CA.
[CertificatesOCSPSerialNumberProblem.zip](https://github.com/strongswan/strongswan/files/10002716/CertificatesOCSPSerialNumberProblem.zip)

Using OpenSSL OCSP server with the command line:
openssl ocsp -index index.txt -port 8101 -rsigner ca.pem -rkey ca.key -CA ca.pem -text

Let me know if you need more information

**Comment by strongX509** [comment] 2022-11-14 15:29
How is the serial number encoded in the X.509 certificate?

* correctly as a two-complements positive integer `02 02 00 9a` ( i.e. `+154`) or
* incorrectly as a two-complements negative integer, `02 01 9a` (i.e. `-66`)

What pki tool did you use to generate the certificate?

**Comment by strongX509** [comment] 2022-11-14 15:40
Hmmm, the serial number of `RSA_4096_2.pem` is correctly encoded as a two-complements positive integer: 
````
 openssl asn1parse -in RSA_4096_2.pem
    0:d=0  hl=4 l=1407 cons: SEQUENCE
    4:d=1  hl=4 l=1127 cons: SEQUENCE
    8:d=2  hl=2 l=   3 cons: cont [ 0 ]
   10:d=3  hl=2 l=   1 prim: INTEGER           :02
   13:d=2  hl=2 l=   2 prim: INTEGER           :9A
````

**Comment by amdrsantos** [comment] 2022-11-14 15:57
> What pki tool did you use to generate the certificate?
They were generated with OpenSSL v1.1.1d

**Comment by strongX509** [comment] 2022-11-15 19:39
I could reproduce the error. It occurs only when the X.509 certificate parsing is done by the `openssl` plugin, i.e. when the `openssl` plugin is loaded before the `x509` plugin, the latter being required for the handling of the OCSP request and response packets
````
charon {
  load = random nonce openssl pem pkcs1 x509 curl revocation vici kernel-netlink socket-default
}
````
The `get_serial()` method of the `openssl` plugin uses the OpenSSL function `X509_get_serialNumber()` which strips the leading `0x00` byte from the positive integer ASN.1 encoding `0x009a` of the serial number.
````
14[LIB] builder L0 CRED_CERTIFICATE - X509 of plugin 'openssl'
14[LIB] builder L1 CRED_PUBLIC_KEY - RSA of plugin 'openssl'
14[IKE] received end entity cert "C=CH, O=strongSwan Project, OU=OCSP, CN=carol@strongswan.org"
````
The stripped serial number is then directly inserted into the OCSP request by the `x509` plugin resulting in an ASN.1 encoding of the negative number `-66` so that the retrieval of the certificate status fails:
````
14[CFG] checking certificate status of "C=CH, O=strongSwan Project, OU=OCSP, CN=carol@strongswan.org"
14[LIB] builder L0 CRED_CERTIFICATE - OCSP_REQUEST of plugin 'x509'
14[CFG]   requesting ocsp status from 'http://ocsp.strongswan.org:8880' ...
14[LIB]   sending request to 'http://ocsp.strongswan.org:8880'...
14[LIB] builder L0 CRED_CERTIFICATE - OCSP_RESPONSE of plugin 'x509'
14[LIB] builder L1 CRED_CERTIFICATE - X509 of plugin 'openssl'
14[LIB] builder L2 CRED_PUBLIC_KEY - RSA of plugin 'openssl'
14[CFG]   ocsp response correctly signed by "C=CH, O=strongSwan Project, OU=OCSP Signing Authority, CN=ocsp.strongswan.org"
14[CFG]   ocsp response contains no status on our certificate
````
When the `x509` plugin is loaded before the `openssl` plugin
````
charon {
  load = random nonce x509 openssl pem pkcs1 curl revocation vici kernel-netlink socket-default
}
````
then the `get_serial()` method of the `x509` plugin extracts the serial number without stripping the leading `0x00` byte
````
14[LIB] builder L0 CRED_CERTIFICATE - X509 of plugin 'x509'
14[LIB] builder L0 CRED_CERTIFICATE - X509 of plugin 'x509'
14[LIB] builder L1 CRED_PUBLIC_KEY - ANY of plugin 'openssl'
14[IKE] received end entity cert "C=CH, O=strongSwan Project, OU=OCSP, CN=carol@strongswan.org"
````
and the status of the certificate with serial number `9a` can be correctly retrieved from the OCSP server:
````
14[CFG] checking certificate status of "C=CH, O=strongSwan Project, OU=OCSP, CN=carol@strongswan.org"
14[LIB] builder L0 CRED_CERTIFICATE - OCSP_REQUEST of plugin 'x509'
14[CFG]   requesting ocsp status from 'http://ocsp.strongswan.org:8880' ...
14[LIB]   sending request to 'http://ocsp.strongswan.org:8880'...
14[LIB] builder L0 CRED_CERTIFICATE - OCSP_RESPONSE of plugin 'x509'
14[LIB] builder L1 CRED_CERTIFICATE - X509 of plugin 'x509'
14[LIB] builder L1 CRED_CERTIFICATE - X509 of plugin 'x509'
14[LIB] builder L2 CRED_PUBLIC_KEY - ANY of plugin 'openssl'
14[CFG]   ocsp response correctly signed by "C=CH, O=strongSwan Project, OU=OCSP Signing Authority, CN=ocsp.strongswan.org"
14[CFG]   ocsp response is valid: until Nov 15 19:04:20 2022
14[CFG] certificate status is good
````
**Intended bug fix:** In the construction of the OCSP request by the `x509` plugin always guarantee a correct  ASN.1 positive integer encoding of the serial number.

**Comment by amdrsantos** [comment] 2022-11-16 09:03
In my configuration, I am not setting plugins to be loaded.
But in the logs I see the plugins being loaded:

```
Nov 15 10:03:42 xmm4-1-1 charon[13423]: 00[DMN] Starting IKE charon daemon (strongSwan 5.9.8, Linux 4.19.81-OpenNetworkLinux-thanos, x86_64)
Nov 15 10:03:42 xmm4-1-1 charon[13423]: 00[LIB] loaded plugins: charon aes des sha2 sha1 md5 nonce x509 revocation constraints pem openssl pkcs8 fips-prf kdf ctr gcm curl kernel-netlink resolve socket-default vici updown error-notify
Nov 15 10:03:42 xmm4-1-1 charon[13423]: 00[JOB] spawning 16 worker threads
```

As a workaround, while the fix is not ready,  should I set my configuration like:
```
charon {
  load = charon aes des sha2 sha1 md5 nonce x509 revocation constraints pem openssl pkcs8 fips-prf kdf ctr gcm curl kernel-netlink resolve socket-default vici updown error-notify
}
```
? 

Or is there a way, at compile time, that forces the `x509` plugin to be loaded before the `openssl` plugin?

**Comment by amdrsantos** [comment] 2022-11-16 12:42
I tried to change de configuration:
`load = nonce x509 openssl pem pkcs8 curl revocation vici kernel-netlink socket-default aes des sha2 sha1 md5 ctr gcm kdf fips-prf constraints updown error-notify resolve`

`Nov 16 12:33:43 xmm4-1-1 charon[5240]: 00[LIB] loaded plugins: charon nonce x509 openssl pem pkcs8 curl revocation vici kernel-netlink socket-default aes des sha2 sha1 md5 ctr gcm kdf fips-prf constraints updown error-notify resolve`

But it did not solve the problem on my end..., it is still sending the OCSP request as -66

**Comment by strongX509** [comment] 2022-11-22 15:44
The patch https://github.com/strongswan/strongswan/commit/42084830f6ac5afda03bcb4943c3f0ac0d142e2a fixes the serial number issue in a comprehensive ways, encompassing serial numbers in X.509 certificates, X.509 attribute certificates, X.509 CRLs, OCSP requests and OCSP responses.

**Comment by amdrsantos** [comment] 2022-11-23 15:23
Thanks Andreas. Do you know normally how long it takes to be integrated into master?

**Comment by strongX509** [comment] 2022-11-23 17:31
My colleague Tobias who is going to review the changes is currently on vacation but will be back next week. Thus the patch will probably go upstream at the end of next week.

**Comment by tobiasbrunner** [comment] 2022-12-02 16:10
> I tried to change de configuration: `load = nonce x509 openssl pem pkcs8 curl revocation vici kernel-netlink socket-default aes des sha2 sha1 md5 ctr gcm kdf fips-prf constraints updown error-notify resolve`
> ...
> But it did not solve the problem on my end..., it is still sending the OCSP request as -66

Note that this plugin order only changes anything if the certificates are DER-encoded. For PEM-encoded certificates you also have to move the _pem_ plugin before the _openssl_ plugin. While both the _x509_ and the _openssl_ plugins can parse DER-encoded certificates, only the _openssl_ plugin can parse PEM-encoded certificates directly, the _x509_ plugin requires the _pem_ plugin to do so. And if that plugin comes after the _openssl_ plugin it's still the latter that parses PEM-encoded certificates.

**Comment by strongX509** [comment] 2022-12-05 19:22
The 1415-serial-numbers branch has been merged with the master

**Closed by strongX509** 2022-12-05 19:22 UTC
Labels: bug
