### ISSUE TITLE
"Invalid ELF image for this architecture" error while running tests suite in strongswan 5.8.4 version

### ISSUE THREAD

**Issue by BadganchiP1234** [strongswan/strongswan#2240] opened 2024-05-08 06:53 UTC
Passed all 12 'threading' test cases
  Running suite 'process':
    Running case 'return values': **qemu-aarch64: /bin/sh: Invalid ELF image for this architecture**
-qemu-aarch64: /bin/sh: Invalid ELF image for this architecture
+
      Failure in 'test_retval_true': retval != 0 (255 != 0) (../../../../strongswan-5.8.4/src/libstrongswan/tests/suites/test_process.c:42, i = 0)
    Running case 'not found': +
    Running case 'echo': **qemu-aarch64: /bin/sh: Invalid ELF image for this architecture**
--
      Failure in 'test_echo': read(out, buf, strlen(msg) + 1) != strlen(msg) (0 != 4) (../../../../strongswan-5.8.4/src/libstrongswan/tests/suites/test_process.c:107, i = 0)
      Failure in 'test_echo_err': read(err, buf, strlen(msg) + 1) != strlen(msg) (22 != 21) (../../../../strongswan-5.8.4/src/libstrongswan/tests/suites/test_process.c:140, i = 0)
    Running case 'env': **qemu-aarch64: /bin/sh: Invalid ELF image for this architecture**
-
      Failure in 'test_env': read(out, buf, sizeof(buf)) > 0 (../../../../strongswan-5.8.4/src/libstrongswan/tests/suites/test_process.c:173, i = 0)
    Running case 'shell': **qemu-aarch64: /bin/sh: Invalid ELF image for this architecture**
-
      Failure in 'test_shell': retval != 3 (255 != 3) (../../../../strongswan-5.8.4/src/libstrongswan/tests/suites/test_process.c:193, i = 0)
  Passed 1/5 'process' test cases

Is the above error is due to running a 32 bit in 64 bit architecture with qemu-aarch64?

Tried running test suites with below command and above error is seen.

qemu-aarch64 libstrongswan_tests

As mentioned in https://github.com/strongswan/strongswan/issues/2237#issuecomment-2097503825 
But in this case test cases execute a shell /bin/sh but still getting "Invalid ELF image for this architecture" error.

Any idea?

**Comment by tobiasbrunner** [comment] 2024-05-08 10:14
How is this not a duplicate of #2237?

**Closed by tobiasbrunner** 2024-05-08 10:14 UTC

**Comment by BadganchiP1234** [comment] 2024-05-08 10:21
@tobiasbrunner 
I saw particular tests suite Running suite 'process': and i found that /bin/sh is called
qemu-aarch64: /usr/bin/dash: Invalid ELF image for this architecture

in this case https://github.com/strongswan/strongswan/issues/2237  /usr/bin/dash is called
 qemu-aarch64: /usr/bin/dash: Invalid ELF image for this architecture

u said https://github.com/strongswan/strongswan/issues/2237#issuecomment-2097503825 it is pointing to /usr/bin/dash so giving this error but in stongswan 5.8.4 https://github.com/strongswan/strongswan/issues/2240 it is pointing to /bin/sh then how come this error we are getting?

**Comment by tobiasbrunner** [comment] 2024-05-08 10:29
What exactly are you not understanding? It doesn't matter what the executable is called, if it's not compatible with the target architecture, it can't be executed.

**Comment by BadganchiP1234** [comment] 2024-05-08 10:33
Is the above error related to 32-bit or 64-bit compatibility?

**Comment by tobiasbrunner** [comment] 2024-05-08 13:33
It's more likely that it's an x86_64 binary and not an ARM64 binary.
