### ISSUE TITLE
unable to install inbound and outbound IPsec SA (SAD) in kernel

### ISSUE THREAD

**Issue by gv74** [strongswan/strongswan#1255] opened 2022-08-26 15:31 UTC
**System (please complete the following information):**
 - OS: Rocky Linux 8.6 (a.k.a. RHEL 8.6)
 - Kernel version (if applicable): 4.18.0-372.19.1.el8_6.x86_64
 - strongSwan version(s): 5.9.6, 5.9.7
 - Tested/confirmed with the latest version: yes

**Describe the bug**
Up to strongswan version 5.9.5 I had no issues. The tunnes are up for months. 
Starting with 5.9.6, strongswan start fine but after about 1 hour it start rekeying in a loop and fail. After a while the tunnel is dropped. I use the same configuration file with 5.9.5, 5.9.6, 5.9.7. During rekeying the following message is issued: "unable to install inbound and outbound IPsec SA (SAD) in kernel" (not sure if is relevant). This also look strange:

```
Fri, 2022-08-26, 17:55:01 15[IKE] <v|1> CHILD_SA rekeying failed, trying again in 8 seconds
Fri, 2022-08-26, 17:55:01 15[CHD] <v|1> CHILD_SA v{1} state change: REKEYING => INSTALLED
Fri, 2022-08-26, 17:55:01 15[CHD] <v|1> CHILD_SA v{96} state change: INSTALLING => DESTROYING
Fri, 2022-08-26, 17:55:01 15[KNL] <v|1> deleting policy m.m.m.125/32 === 192.168.1.0/24 in
Fri, 2022-08-26, 17:55:01 15[KNL] <v|1> policy still used by another CHILD_SA, not removed
Fri, 2022-08-26, 17:55:01 15[KNL] <v|1> not updating policy m.m.m.125/32 === 192.168.1.0/24 in [priority 371327, refcount 1]
Fri, 2022-08-26, 17:55:01 15[KNL] <v|1> deleting policy m.m.m.125/32 === 192.168.1.0/24 fwd
Fri, 2022-08-26, 17:55:01 15[KNL] <v|1> policy still used by another CHILD_SA, not removed
Fri, 2022-08-26, 17:55:01 15[KNL] <v|1> not updating policy m.m.m.125/32 === 192.168.1.0/24 fwd [priority 371327, refcount 1]
Fri, 2022-08-26, 17:55:01 15[KNL] <v|1> deleting SAD entry with SPI c6d14020
Fri, 2022-08-26, 17:55:01 15[KNL] <v|1> deleted SAD entry with SPI c6d14020
```

[charon_debug.log.gz](https://github.com/strongswan/strongswan/files/9434434/charon_debug.log.gz)
[v.conf.txt](https://github.com/strongswan/strongswan/files/9434437/v.conf.txt)

**Logs/Backtraces**
Log generated as described here: https://docs.strongswan.org/docs/5.9/support/helpRequests.html

```
filelog {
    # any arbitrary name without dots for the section instead of the one given here
    charon-debug-log {
      # this setting is required with 5.7.0 and newer if the path contains dots
      path = /var/log/charon_debug.log
      time_format = %a, %Y-%m-%d, %H:%M:%S
      default = 2
      net = 1
      enc = 1
      asn = 1
      job = 1
      ike_name = yes
      append = no
      flush_line = yes
    }
  }
```

**Comment by gv74** [comment] 2022-08-27 11:20
> Try to increase the log level for _chd_ to 4 to see additional messages there.

See charon_debug-2022.08.27-modp_8192.log.gz
[charon_debug-2022.08.27-modp_8192.log.gz](https://github.com/strongswan/strongswan/files/9437837/charon_debug-2022.08.27-modp_8192.log.gz)

> You could also try if it works if you use a different DH algorithm than _modp8192_ in your ESP proposal.

Switching for modp_8192 to ecp_256 and rekeying works again. Thank you!
[charon_debug-2022.08.27-ecp256.log.gz](https://github.com/strongswan/strongswan/files/9437838/charon_debug-2022.08.27-ecp256.log.gz)

**Comment by tobiasbrunner** [comment] 2022-08-29 08:24
Thanks for the log. The problem is exactly where I suspected. The reason is that OpenSSL fails to calculate HKDF-Expand() with the given seed. Which can be explained by this statement on the [man page for `EVP_PKEY_CTX_add1_hkdf_info()`](https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_CTX_add1_hkdf_info.html):

> The total length of the info buffer cannot exceed 1024 bytes in length: this should be more than enough for any normal use of HKDF.

That's unfortunately slightly too little for _modp8192_ whose secret itself is 1024 bytes, but to that two 32 byte nonces are added  (= 1088 bytes). These could even be longer as the maximum length per nonce is defined as 256 bytes by RFC 7296.

This issue was fixed with OpenSSL 3 where the buffer was increased to 2048 bytes (see https://github.com/openssl/openssl/commit/20c2876f24d0ccf9581ace08c7882d544d2588ea). So I guess you are not using OpenSSL 3 yet. The man page also hasn't been updated yet (my PR for that is at https://github.com/openssl/openssl/pull/19085).

If you still want to use _modp8192_, you could increase the priority of the _kdf_ plugin (see [here](https://docs.strongswan.org/docs/5.9/plugins/pluginLoad.html#_runtime_plugin_configuration) for details), which does not have such a limit.

**Closed by tobiasbrunner** 2022-08-29 08:24 UTC
Labels: bug

**Comment by gv74** [comment] 2022-08-29 11:30
Thank you for your help!
