### ISSUE TITLE
Crash when setting ipcomp or hostaccess when using GCC 12

### ISSUE THREAD

**Issue by pmconrad** [strongswan/strongswan#1053] opened 2022-05-18 06:20 UTC
**System (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - Kernel version (if applicable): 5.17.5
 - strongSwan version(s): 5.9.6
 - Tested/confirmed with the latest version: no

**Describe the bug**
Minimal config:
```
conn-defaults {
        vips = 0.0.0.0
}
local-defaults {
        certs = <file>.pem
}
remote-defaults {
        cacerts = <cafile>.pem
}
child-defaults {
#        ipcomp = yes
        start_action = trap
#        hostaccess = yes
        updown = /usr/libexec/ipsec/_updown iptables
        mode = tunnel
}
connections {
    harz : conn-defaults {
        remote_addrs = 242.242.242.242 # actual address doesn't matter
        local : local-defaults {
        }
        remote : remote-defaults {
        }
        children {
            harz : child-defaults {
            }
        }
    }
}
secrets {
}
pools {
}
authorities {
    stubb {
        cacert = <cafile>.pem
    }
}
```
After removing the `#` from the `ipcomp` line or the `hostaccess` line, `systemctl restart strongswan` reports a crash, see below.

My actual configuration had been working fine until I upgraded to 5.9.6 a couple of days ago.

**To Reproduce**
1. Create `swanctl.conf` as above
2. `systemctl restart strongswan`

**Expected behavior**
Connections should be set up successfully, of course.

**Logs/Backtraces**
```
...
May 18 08:01:58 soot charon-systemd[20434]: builder L3 CRED_PUBLIC_KEY - RSA of plugin 'pkcs1'
May 18 08:01:58 soot charon-systemd[20434]: L0 - RSAPublicKey:
May 18 08:01:58 soot charon-systemd[20434]: L1 - modulus:
May 18 08:01:58 soot charon-systemd[20434]: L1 - publicExponent:
May 18 08:01:58 soot charon-systemd[20434]: builder L4 CRED_PUBLIC_KEY - RSA of plugin 'pkcs1'
May 18 08:01:58 soot charon-systemd[20434]: builder L4 CRED_PUBLIC_KEY - RSA of plugin 'pgp'
May 18 08:01:58 soot charon-systemd[20434]: builder L4 CRED_PUBLIC_KEY - RSA of plugin 'dnskey'
May 18 08:01:58 soot charon-systemd[20434]: builder L4 CRED_PUBLIC_KEY - RSA of plugin 'openssl'
May 18 08:01:58 soot charon-systemd[20434]: -- < --
May 18 08:01:58 soot charon-systemd[20434]: -- < --
May 18 08:01:58 soot charon-systemd[20434]: L2 - optional extensions:
May 18 08:01:58 soot charon-systemd[20434]: L3 - extensions:
May 18 08:01:58 soot charon-systemd[20434]: L4 - extension:
May 18 08:01:58 soot charon-systemd[20434]: L5 - extnID:
May 18 08:01:58 soot charon-systemd[20434]:   'subjectKeyIdentifier'
May 18 08:01:58 soot charon-systemd[20434]: L5 - critical:
May 18 08:01:58 soot charon-systemd[20434]:   FALSE
May 18 08:01:58 soot charon-systemd[20434]: L5 - extnValue:
May 18 08:01:58 soot charon-systemd[20434]: L6 - keyIdentifier:
May 18 08:01:58 soot charon-systemd[20434]: L4 - extension:
May 18 08:01:58 soot charon-systemd[20434]: L5 - extnID:
May 18 08:01:58 soot charon-systemd[20434]:   'authorityKeyIdentifier'
May 18 08:01:58 soot charon-systemd[20434]: L5 - critical:
May 18 08:01:58 soot charon-systemd[20434]:   FALSE
May 18 08:01:58 soot charon-systemd[20434]: L5 - extnValue:
May 18 08:01:58 soot charon-systemd[20434]: L6 - authorityKeyIdentifier:
May 18 08:01:58 soot charon-systemd[20434]: L7 - keyIdentifier:
May 18 08:01:58 soot charon-systemd[20434]: L4 - extension:
May 18 08:01:58 soot charon-systemd[20434]: L5 - extnID:
May 18 08:01:58 soot charon-systemd[20434]:   'basicConstraints'
May 18 08:01:58 soot charon-systemd[20434]: L5 - critical:
May 18 08:01:58 soot charon-systemd[20434]:   FALSE
May 18 08:01:58 soot charon-systemd[20434]: L5 - extnValue:
May 18 08:01:58 soot charon-systemd[20434]: L6 - basicConstraints:
May 18 08:01:58 soot charon-systemd[20434]: L7 - CA:
May 18 08:01:58 soot charon-systemd[20434]:   TRUE
May 18 08:01:58 soot charon-systemd[20434]: L1 - signatureAlgorithm:
May 18 08:01:58 soot charon-systemd[20434]: L2 - algorithmIdentifier:
May 18 08:01:58 soot charon-systemd[20434]: L3 - algorithm:
May 18 08:01:58 soot charon-systemd[20434]:   'sha-1WithRSAEncryption'
May 18 08:01:58 soot charon-systemd[20434]: L3 - parameters:
May 18 08:01:58 soot charon-systemd[20434]: L1 - signatureValue:
May 18 08:01:58 soot charon-systemd[20434]: thread 4 received 11
May 18 08:01:58 soot charon-systemd[20434]:  dumping 20 stack frame addresses:
May 18 08:01:58 soot charon-systemd[20434]:   /lib64/libc.so.6 @ 0x7fa25ffca000 [0x7fa2600207c0]
May 18 08:01:58 soot charon-systemd[20434]:     -> ??:?
May 18 08:01:58 soot charon-systemd[20434]:   /usr/lib64/ipsec/plugins/libstrongswan-vici.so @ 0x7fa25e7bd000 [0x7fa25e7d3311]
May 18 08:01:58 soot charon-systemd[20461]: addr2line: DWARF error: unable to read alt ref 57413
May 18 08:01:58 soot charon-systemd[20434]:     -> :?
May 18 08:01:58 soot charon-systemd[20434]:   /usr/lib64/ipsec/plugins/libstrongswan-vici.so @ 0x7fa25e7bd000 [0x7fa25e7cad5b]
May 18 08:01:58 soot charon-systemd[20462]: addr2line: DWARF error: unable to read alt ref 12804
May 18 08:01:58 soot charon-systemd[20462]: addr2line: DWARF error: unable to read alt ref 11037
May 18 08:01:58 soot charon-systemd[20462]: addr2line: DWARF error: unable to read alt ref 57413
May 18 08:01:58 soot charon-systemd[20434]:     -> :?
May 18 08:01:58 soot charon-systemd[20434]:   /usr/lib64/ipsec/plugins/libstrongswan-vici.so @ 0x7fa25e7bd000 [0x7fa25e7d05ab]
May 18 08:01:58 soot charon-systemd[20463]: addr2line: DWARF error: unable to read alt ref 12804
May 18 08:01:58 soot charon-systemd[20463]: addr2line: DWARF error: unable to read alt ref 11037
May 18 08:01:58 soot charon-systemd[20463]: addr2line: DWARF error: unable to read alt ref 57413
May 18 08:01:58 soot charon-systemd[20434]:     -> :?
May 18 08:01:58 soot charon-systemd[20434]:   /usr/lib64/ipsec/plugins/libstrongswan-vici.so @ 0x7fa25e7bd000 [0x7fa25e7d0d7d]
May 18 08:01:58 soot charon-systemd[20464]: addr2line: DWARF error: unable to read alt ref 12804
May 18 08:01:58 soot charon-systemd[20464]: addr2line: DWARF error: unable to read alt ref 11037
May 18 08:01:58 soot charon-systemd[20464]: addr2line: DWARF error: unable to read alt ref 57413
May 18 08:01:58 soot charon-systemd[20434]:     -> :?
May 18 08:01:58 soot charon-systemd[20434]:   /usr/lib64/ipsec/plugins/libstrongswan-vici.so @ 0x7fa25e7bd000 [0x7fa25e7c3fb9]
May 18 08:01:58 soot charon-systemd[20466]: addr2line: DWARF error: unable to read alt ref 12804
May 18 08:01:58 soot charon-systemd[20466]: addr2line: DWARF error: unable to read alt ref 11037
May 18 08:01:58 soot charon-systemd[20466]: addr2line: DWARF error: unable to read alt ref 17210
May 18 08:01:58 soot charon-systemd[20434]:     -> :?
May 18 08:01:58 soot charon-systemd[20434]:   /usr/lib64/ipsec/plugins/libstrongswan-vici.so @ 0x7fa25e7bd000 [0x7fa25e7cc3a5]
May 18 08:01:58 soot charon-systemd[20467]: addr2line: DWARF error: unable to read alt ref 12804
May 18 08:01:58 soot charon-systemd[20467]: addr2line: DWARF error: unable to read alt ref 11037
May 18 08:01:59 soot charon-systemd[20467]: addr2line: DWARF error: unable to read alt ref 57413
...
May 18 08:02:02 soot charon-systemd[20434]:   /usr/lib64/ipsec/plugins/libstrongswan-vici.so @ 0x7fa25e7bd000 [0x7fa25e7c2649]
May 18 08:02:02 soot charon-systemd[20496]: addr2line: DWARF error: unable to read alt ref 12804
May 18 08:02:02 soot charon-systemd[20496]: addr2line: DWARF error: unable to read alt ref 11037
May 18 08:02:02 soot charon-systemd[20496]: addr2line: DWARF error: unable to read alt ref 17210
May 18 08:02:02 soot charon-systemd[20434]:     -> :?
May 18 08:02:02 soot charon-systemd[20434]:   /usr/lib64/ipsec/libstrongswan.so.0 @ 0x7fa26038c000 [0x7fa2603c3fe2]
May 18 08:02:02 soot charon-systemd[20497]: addr2line: DWARF error: unable to read alt ref 12804
May 18 08:02:02 soot charon-systemd[20497]: addr2line: DWARF error: unable to read alt ref 10778
May 18 08:02:02 soot charon-systemd[20497]: addr2line: DWARF error: unable to read alt ref 48052
May 18 08:02:02 soot charon-systemd[20434]:     -> :?
May 18 08:02:02 soot charon-systemd[20434]:   /usr/lib64/ipsec/libstrongswan.so.0 @ 0x7fa26038c000 [0x7fa2603cb6d6]
May 18 08:02:02 soot charon-systemd[20498]: addr2line: DWARF error: unable to read alt ref 12804
May 18 08:02:02 soot charon-systemd[20498]: addr2line: DWARF error: unable to read alt ref 10778
May 18 08:02:02 soot charon-systemd[20498]: addr2line: DWARF error: unable to read alt ref 48052
May 18 08:02:02 soot charon-systemd[20434]:     -> :?
May 18 08:02:02 soot charon-systemd[20434]:   /usr/lib64/ipsec/libstrongswan.so.0 @ 0x7fa26038c000 [0x7fa2603d84ee]
May 18 08:02:02 soot charon-systemd[20499]: addr2line: DWARF error: unable to read alt ref 12804
May 18 08:02:02 soot charon-systemd[20499]: addr2line: DWARF error: unable to read alt ref 10778
May 18 08:02:02 soot charon-systemd[20499]: addr2line: DWARF error: unable to read alt ref 48052
May 18 08:02:02 soot charon-systemd[20434]:     -> :?
May 18 08:02:02 soot charon-systemd[20434]:   /lib64/libc.so.6 @ 0x7fa25ffca000 [0x7fa260071607]
May 18 08:02:02 soot charon-systemd[20434]:     -> ??:?
May 18 08:02:02 soot charon-systemd[20434]:   /lib64/libc.so.6 @ 0x7fa25ffca000 [0x7fa2600fba10]
May 18 08:02:02 soot charon-systemd[20434]:     -> ??:?
May 18 08:02:02 soot charon-systemd[20434]: killing ourself, received critical signal
May 18 08:02:02 soot swanctl[20453]: load-conn request failed: Success
May 18 08:02:02 soot swanctl[20453]: loaded 0 of 1 connections, 1 failed to load, 0 unloaded
May 18 08:02:02 soot swanctl[20453]: loaded certificate from '/etc/swanctl/x509/<file>.pem'
May 18 08:02:02 soot swanctl[20453]: loaded certificate from '/etc/swanctl/x509ca/<cafile>.pem'
May 18 08:02:02 soot swanctl[20453]: loaded rsa key from '/etc/swanctl/rsa/<file>.key'
May 18 08:02:02 soot swanctl[20453]: loaded authority '<cafile>'
May 18 08:02:02 soot swanctl[20453]: successfully loaded 1 authorities, 0 unloaded
May 18 08:02:02 soot swanctl[20453]: no pools found, 0 unloaded
May 18 08:02:02 soot systemd[1]: strongswan.service: Control process exited, code=exited, status=22/n/a
May 18 08:02:02 soot systemd[1]: strongswan.service: Main process exited, code=dumped, status=6/ABRT
May 18 08:02:02 soot systemd[1]: strongswan.service: Failed with result 'exit-code'.
May 18 08:02:02 soot systemd[1]: Failed to start strongSwan IPsec IKEv1/IKEv2 daemon using swanctl.
May 18 08:02:02 soot systemd[1]: strongswan.service: Consumed 4.098s CPU time.
```
(The `addr2line` errors are caused from my failed attempt to load debugging symbols I think.)

**Additional context**

**Comment by tobiasbrunner** [comment] 2022-05-18 07:39
> After removing the # from the ipcomp line or the hostaccess line, systemctl restart strongswan reports a crash, see below.

I can't reproduce anything like that.

> until I upgraded to 5.9.6 a couple of days ago

How exactly did you do that? Did you build it yourself? If not, did you ever do so before?

**Comment by pmconrad** [comment] 2022-05-18 09:20
> I can't reproduce anything like that.

Maybe an issue with other parts of the configuration? Any idea how to further debug this?

> How exactly did you do that?

I'm using the package provided by openSUSE, i. e. I upgraded using their package management tool `zypper dup`.
No, I didn't build it myself nor have I ever done so.

This is how they build it: https://build.opensuse.org/package/show/openSUSE:Factory/strongswan

**Comment by tobiasbrunner** [comment] 2022-05-18 09:44
> Any idea how to further debug this?

Without proper backtrace it's difficult to say more. Maybe try this:

    mv /etc/swanctl /etc/swanctl-debug
    systemctl restart strongswan

Then attach `gdb` to the running daemon (try `systemctl status strongswan` to determine the executable and PID, then run `gdb <path/to/charon-systemd> <pid>` and `cont` in GDB). Afterwards, load the config manually to trigger the crash:

    swanctl --file /etc/swanctl-debug/swanctl.conf --load-all

Then in GDB run `thread apply all bt full` to hopefully get proper backtraces.

**Comment by tobiasbrunner** [comment] 2022-05-18 14:21
In both cases it looks like the pointer to which the parsed value is written is NULL. Since that's basically impossible (the pointer passed to `parse_bool()` by `parse_option()` is that of a local variable on the stack), I've really no idea what's going on here.

**Comment by pmconrad** [comment] 2022-05-18 15:05
Could be a gcc problem (or a problem with your CALLBACK macro). AFAIK Tumbleweed recently upgraded to gcc-12, so strongswan is not the only thing that has changed.

I have created a minimal C example that also segfaults with a NULL `out` parameter:
```
peter@soot:/tmp> cat >/tmp/test.c <<__EOC__
> #include <stdbool.h>
> #include <stdio.h>
> #include <string.h>
> 
> #define CALLBACK(name, ret, param1, ...) \
>         static ret _cb_##name(union {void *_generic; param1;} \
>         __attribute__((transparent_union)), ##__VA_ARGS__); \
>         static typeof(_cb_##name) *name = (typeof(_cb_##name)*)_cb_##name; \
>         static ret _cb_##name(param1, ##__VA_ARGS__)
> 
> CALLBACK(parse, bool, bool* out, char* in) {
>     *out = !strcmp("yes", in);
>     return true;
> }
> 
> int main(int argc, char **argv) {
>     bool val;
> 
>     if (argc < 2) {
>         printf("Missing argument\n");
>         return 1;
>     }
>     parse(&val, argv[1]);
>     printf("Arg is %d\n", val); 
> }
> __EOC__
peter@soot:/tmp> gcc --version
gcc (SUSE Linux) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.

peter@soot:/tmp> gcc -o /tmp/test -O1 /tmp/test.c
peter@soot:/tmp> /tmp/test yes
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

If I change the function declaration to plain `bool parse(bool* out, char* in)` instead of using the CALLBACK macro it works as expected, so I'm not sure if gcc is at fault or the macro.

**Comment by pmconrad** [comment] 2022-05-19 06:43
Reported as [gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105654). Will see what they have to say.

**Comment by tobiasbrunner** [comment] 2022-05-19 07:48
Thanks for looking into this and reporting it. Not sure if it's a regression or if we relied on undefined behavior with that macro, but it worked fine in GCC and clang since it was added 8 years ago.

I've done some experiments at godbolt.org and as you already found, the compiler passes `0` if the callback function is called directly, see the `xor     edi, edi`  instruction it produces before the call [here](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:1,endLineNumber:8,positionColumn:1,positionLineNumber:8,selectionStartColumn:1,selectionStartLineNumber:8,startColumn:1,startLineNumber:8),source:'%23include+%3Cstdbool.h%3E%0A%23include+%3Cstdio.h%3E%0A%23include+%3Cstring.h%3E%0A+%0A%23define+CALLBACK(name,+ret,+param1,+...)+%5C%0A++++++++static+ret+_cb_%23%23name(union+%7Bvoid+*_generic%3B+param1%3B%7D+%5C%0A++++++++__attribute__((transparent_union)),+%23%23__VA_ARGS__)%3B+%5C%0A++++++++static+typeof(_cb_%23%23name)+*name+%3D+(typeof(_cb_%23%23name)*)_cb_%23%23name%3B+%5C%0A++++++++static+ret+_cb_%23%23name(param1,+%23%23__VA_ARGS__)%0A%0ACALLBACK(parse,+bool,+bool*+out,+char*+in)+%7B%0A++++*out+%3D+!!strcmp(%22yes%22,+in)%3B%0A++++return+true%3B%0A%7D%0A+%0Aint+main(int+argc,+char+**argv)+%7B%0A++++bool+val%3D+0%3B%0A+%0A++++if+(argc+%3C+2)+%7B%0A++++++++printf(%22Missing+argument%5Cn%22)%3B%0A++++++++return+1%3B%0A++++%7D%0A++++parse(%26val,+argv%5B1%5D)%3B%0A++++printf(%22Arg+is+%25d%5Cn%22,+val)%3B+%0A%7D'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:cg121,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,libs:!(),options:'-Wall+-g+-Wextra+-Wno-unused+-Wno-unused-parameter+-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+gcc+12.1+(C,+Editor+%231,+Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'0',compilationPanelShown:'0',compiler:cg121,compilerOutShown:'0',execArgs:yes,execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:___c,libs:!(),options:'-Wall+-g+-Wextra+-Wno-unused+-Wno-unused-parameter+-O2',source:1,stdinPanelShown:'1',tree:'1',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+gcc+12.1+(C,+Editor+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

Since we use the macro all over the place for callbacks, my assumption was that it works fine if it's called indirectly via a function pointer that has `void*` as first argument (e.g. in `vici_config.c` for actual boolean settings like `encap` or `mobike`). Which lead me to a possible fix for the macro:

```diff
diff --git a/src/libstrongswan/utils/utils/object.h b/src/libstrongswan/utils/u>
index 174ea812a143..da580c01af87 100644
--- a/src/libstrongswan/utils/utils/object.h
+++ b/src/libstrongswan/utils/utils/object.h
@@ -120,7 +120,7 @@
 #define CALLBACK(name, ret, param1, ...) \
    static ret _cb_##name(union {void *_generic; param1;} \
    __attribute__((transparent_union)), ##__VA_ARGS__); \
-   static typeof(_cb_##name) *name = (typeof(_cb_##name)*)_cb_##name; \
+   static ret (*name)(void*, ##__VA_ARGS__) = _cb_##name; \
    static ret _cb_##name(param1, ##__VA_ARGS__)
 
 /**
```
This seems to fix the issue, as can be seen [here](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:2,endLineNumber:25,positionColumn:2,positionLineNumber:25,selectionStartColumn:2,selectionStartLineNumber:25,startColumn:2,startLineNumber:25),source:'%23include+%3Cstdbool.h%3E%0A%23include+%3Cstdio.h%3E%0A%23include+%3Cstring.h%3E%0A+%0A%23define+CALLBACK(name,+ret,+param1,+...)+%5C%0A++++++++static+ret+_cb_%23%23name(union+%7Bvoid+*_generic%3B+param1%3B%7D+%5C%0A++++++++__attribute__((transparent_union)),+%23%23__VA_ARGS__)%3B+%5C%0A++++++++static+ret+(*name)(void*,%23%23__VA_ARGS__)+%3D+_cb_%23%23name%3B+%5C%0A++++++++static+ret+_cb_%23%23name(param1,+%23%23__VA_ARGS__)%0A%0ACALLBACK(parse,+bool,+bool*+out,+char*+in)+%7B%0A++++*out+%3D+!!strcmp(%22yes%22,+in)%3B%0A++++return+true%3B%0A%7D%0A+%0Aint+main(int+argc,+char+**argv)+%7B%0A++++bool+val%3D+0%3B%0A+%0A++++if+(argc+%3C+2)+%7B%0A++++++++printf(%22Missing+argument%5Cn%22)%3B%0A++++++++return+1%3B%0A++++%7D%0A++++parse(%26val,+argv%5B1%5D)%3B%0A++++printf(%22Arg+is+%25d%5Cn%22,+val)%3B+%0A%7D'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:cg121,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,libs:!(),options:'-Wall+-g+-Wextra+-Wno-unused+-Wno-unused-parameter+-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+gcc+12.1+(C,+Editor+%231,+Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'0',compilationPanelShown:'0',compiler:cg121,compilerOutShown:'0',execArgs:yes,execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:___c,libs:!(),options:'-Wall+-g+-Wextra+-Wno-unused+-Wno-unused-parameter+-O2',source:1,stdinPanelShown:'1',tree:'1',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+gcc+12.1+(C,+Editor+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

**Comment by pmconrad** [comment] 2022-05-22 10:32
I can confirm that the patch fixes the problem at least for me.
I see there are other similar macros, maybe you'll want to fix these too.

**Comment by tobiasbrunner** [comment] 2022-05-23 14:15
Thanks for testing. Yes, `CALLBACK2` will need the same fix (see the _1053-gcc12_ branch). But it doesn't seem that the `METHOD*` macros are affected. For one, the `_<name>` functions declared by them are generally only assigned to function pointers. But even when explicitly calling `_<name>` functions directly, I was unable to trigger this issue. Might be because we never assign anything to the first pointer (they are always pointers to structs and we only access their members, which apparently doesn't trigger the issue).

**Comment by tobiasbrunner** [comment] 2022-06-27 12:08
There hasn't been an update to the GCC bug report so far. Let's just close this for now with the workaround for the two `CALLBACK` macros discussed above.

**Closed** 2022-06-27 12:08 UTC
Labels: bug
