### ISSUE TITLE
Strongswan Responder rekey IKE, CHILD_SA rekey fails with INVALID_SPI alert

### ISSUE THREAD

**Issue by ssussman1971** [strongswan/strongswan#309] opened 2021-04-07 19:59 UTC
The scenario I am seeing is as follows:

* client (initial Initiator) establishes IKE with IPSec SA
* server (initial Responder) initiates CREATE_CHILD_SA request to Initiator successfully.
* Some time later server (Responder) Initiates IKE Rekey request to client (initiator).
* Rekey completes and roles of initiator and responder are now swapped. Client is now Responder and Server is now Initiator
* Server (new Initiator) requests Rekey of CHILD_SA to client (new Responder)
* Client (new responder) reply with CREATE_CHILD_SA response. 
* Server (new Initiator) reports checkout_by_message() fails due to INVALID_IKE_SPI
* Initiator SPI and Responder SPI are correct in CREATE_CHILD_SA Rekey request/replys
* after 4 seconds Server (new initiator) retransmits CREATE_CHILD_SA rekey request
* client (new responder) responds and this time the server successfully checks out and processes the response
* 
Strongswan 5.8.4 (confirmed in latest release as well)

Apr  7 20:10:14 10[JOB]   watching 18 for reading
Apr  7 20:10:14 10[JOB] watcher going to poll() 6 fds
Apr  7 20:10:14 02[KNL] received a XFRM_MSG_EXPIRE
**Apr  7 20:10:14 02[KNL] creating rekey job for CHILD_SA ESP/0xcdf894e8/20.129.3.210
Apr  7 20:10:14 02[MGR] checkout IKEv2 SA with SPIs a1a169042c232d2f_i 6ed6ea0e00000000_r**
Apr  7 20:10:14 10[JOB] watcher got notification, rebuilding
Apr  7 20:10:14 10[JOB]   watching 9 for reading
Apr  7 20:10:14 10[JOB]   watching 15 for reading
Apr  7 20:10:14 10[JOB]   watching 16 for reading
Apr  7 20:10:14 02[MGR] IKE_SA casa[2] successfully checked out
Apr  7 20:10:14 10[JOB]   watching 17 for reading
Apr  7 20:10:14 10[JOB]   watching 20 for reading
Apr  7 20:10:14 10[JOB]   watching 18 for reading
Apr  7 20:10:14 10[JOB] watcher going to poll() 7 fds
Apr  7 20:10:14 02[IKE] <casa|2> queueing CHILD_REKEY task
Apr  7 20:10:14 02[IKE] <casa|2> activating new tasks
.
.
.
Apr  7 20:10:14 01[ENC] parsing HEADER payload finished
Apr  7 20:10:14 01[ENC] parsed a CREATE_CHILD_SA response header
Apr  7 20:10:14 01[NET] waiting for data on sockets
**Apr  7 20:10:14 15[MGR] checkout IKEv2 SA by message with SPIs a1a169042c232d2f_i 6ed6ea0e00000000_r**
**Apr  7 20:10:14 15[IKE] ALERT: ALERT_INVALID_IKE_SPI RESPONSE message ID 0 reported with initiator SPI a1a169042c232d2f responder SPI 6ed6ea0e00000000 .**
Apr  7 20:10:14 15[MGR] IKE_SA checkout not successful
.
.
.
Apr  7 20:10:18 12[JOB] got event, queuing job for execution
Apr  7 20:10:18 12[JOB] next event in 30s 7ms, waiting
**Apr  7 20:10:18 14[MGR] checkout IKEv2 SA with SPIs a1a169042c232d2f_i 6ed6ea0e00000000_r**
Apr  7 20:10:18 14[MGR] IKE_SA casa[2] successfully checked out
Apr  7 20:10:18 14[IKE] <casa|2> retransmit 1 of request with message ID 0
Apr  7 20:10:18 14[CFG] <casa|2> ALERT_RETRANSMIT_SEND for Initiator SPI a1a169042c232d2f and Responder SPI 6ed6ea0e00000000.
Apr  7 20:10:18 14[CFG] <casa|2> IKE 2 SK_EI: => 0 bytes @ (nil)
Apr  7 20:10:18 14[CFG] <casa|2> IKE 2 SK_ER: => 0 bytes @ (nil)
Apr  7 20:10:18 14[CFG] <casa|2> IKE 2 SK_AI: => 20 bytes @ 0x7fc8380051b0
Apr  7 20:10:18 14[CFG] <casa|2>    0: A2 07 E7 9B 1D 48 A8 EA 85 EB 9B 7C AA 4B 62 4C  .....H.....|.KbL
Apr  7 20:10:18 14[CFG] <casa|2>   16: 4A 34 BC 63                                      J4.c
Apr  7 20:10:18 14[CFG] <casa|2> IKE 2 SK_AR: => 20 bytes @ 0x7fc8380051d0
Apr  7 20:10:18 14[CFG] <casa|2>    0: 2E 74 91 EF DB 0E 18 B2 41 95 44 C1 01 CB DC D1  .t......A.D.....
Apr  7 20:10:18 14[CFG] <casa|2>   16: AF F3 5A 07                                      ..Z.
Apr  7 20:10:18 14[NET] <casa|2> sending packet: from 20.129.3.210[4500] to 20.128.3.189[10000] (393 bytes)
Apr  7 20:10:18 14[MGR] <casa|2> checkin IKE_SA casa[2]
Apr  7 20:10:18 12[JOB] next event in 7s 199ms, waiting
Apr  7 20:10:18 14[MGR] <casa|2> checkin of IKE_SA successful
Apr  7 20:10:18 13[NET] sending packet: from 20.129.3.210[4500] to 20.128.3.189[10000]
Apr  7 20:10:18 01[NET] received packet => 193 bytes @ 0x7fc8646274c0
.
.
.

Apr  7 20:10:18 01[ENC] parsing HEADER payload finished
Apr  7 20:10:18 01[ENC] parsed a CREATE_CHILD_SA response header
Apr  7 20:10:18 01[NET] waiting for data on sockets
**Apr  7 20:10:18 05[MGR] checkout IKEv2 SA by message with SPIs a1a169042c232d2f_i 6ed6ea0e00000000_r**
**Apr  7 20:10:18 05[MGR] IKE_SA casa[2] successfully checked out**
Apr  7 20:10:18 05[NET] <casa|2> received packet: from 20.128.3.189[10000] to 20.129.3.210[4500] (189 bytes)
Apr  7 20:10:18 05[ENC] <casa|2> parsing body of message, first payload is ENCRYPTED

Due to proprietary messages and logs in the Strongswan logs and packet captures I would prefer not to post those in full here but can provide them securely if needed.

**Comment by tobiasbrunner** [comment] 2021-05-06 15:03
This sounds weird. And I can't reproduce it with strongSwan on both sides. So I don't we get any further without more information.

**Comment by tobiasbrunner** [comment] 2023-05-26 11:49
Closing this as no additional information was provided.

**Closed by tobiasbrunner** 2023-05-26 11:49 UTC
