### ISSUE TITLE
5.9.7" test suite is failing in one unit

### ISSUE THREAD

**Issue by kloczek** [strongswan/strongswan#1199] opened 2022-08-07 23:33 UTC
source code configured with:
```spec
%configure \
        CPPFLAGS="-DSTARTER_ALLOW_NON_ROOT" \
        --bindir=%{_libexecdir}/strongswan \
        --disable-static \
        --enable-acert \
        --enable-aikgen \
        --enable-bypass-lan \
        --enable-ccm \
        --enable-chapoly \
        --enable-cmd \
        --enable-ctr \
        --enable-curl \
        --enable-dhcp \
        --enable-duplicheck \
        --enable-eap-aka \
        --enable-eap-aka-3gpp \
        --enable-eap-aka-3gpp2 \
        --enable-eap-dynamic \
        --enable-eap-gtc \
        --enable-eap-identity \
        --enable-eap-md5 \
        --enable-eap-mschapv2 \
        --enable-eap-peap \
        --enable-eap-radius \
        --enable-eap-sim \
        --enable-eap-sim-file \
        --enable-eap-tls \
        --enable-eap-tnc \
        --enable-eap-ttls \
        --enable-ext-auth \
        --enable-farp \
        --enable-gcm \
        --enable-gcrypt \
        --enable-ha \
        --enable-imc-attestation \
        --enable-imc-hcd \
        --enable-imc-os \
        --enable-imc-scanner \
        --enable-imc-swid \
        --enable-imc-swima \
        --enable-imc-test \
        --enable-imv-attestation \
        --enable-imv-hcd \
        --enable-imv-os \
        --enable-imv-scanner  \
        --enable-imv-swid \
        --enable-imv-swima \
        --enable-imv-test \
        --enable-ipseckey \
        --enable-led \
        --enable-md4 \
        --enable-newhope \
        --enable-nm \
        --enable-openssl \
        --enable-pkcs11 \
        --enable-sql \
        --enable-sqlite \
        --enable-swanctl \
        --enable-systemd \
        --enable-tnccs-11 \
        --enable-tnccs-20 \
        --enable-tnccs-dynamic \
        --enable-tnc-ifmap \
        --enable-tnc-imc \
        --enable-tnc-imv \
        --enable-tnc-pdp \
        --enable-tpm \
        --enable-tss-tss2 \
        --enable-unity \
        --enable-vici \
        --enable-xauth-eap \
        --enable-xauth-noauth \
        --enable-xauth-pam \
        --sysconfdir=%{_sysconfdir}/strongswan \
        --with-capabilities=libcap \
        --with-fips-mode=2 \
        --with-ipsecdir=%{_libexecdir}/strongswan \
        --with-ipseclibdir=%{_libdir}/strongswan \
        --with-ipsec-script=strongswan \
        --with-piddir=%{_rundir}/strongswan \
        --enable-aesni \
        --enable-kernel-libipsec \
        %{nil}
```
And test suite is failing
```console
make[6]: Entering directory '/home/tkloczko/rpmbuild/BUILD/strongswan-5.9.7/src/libstrongswan/plugins/newhope/tests'
no files found matching '/etc/strongswan/strongswan.conf'
abort initialization due to invalid configuration
unable to load OpenSSL FIPS provider
plugin 'openssl': failed to load - openssl_plugin_create returned NULL
loaded plugins: pkcs11 aesni aes des rc2 sha2 sha1 md4 md5 mgf1 random nonce x509 revocation constraints acert pubkey pkcs1 pkcs7 pkcs12 pgp dnskey sshkey pem gcrypt pkcs8 fips-prf gmp curve25519 chapoly xcbc cmac hmac kdf ctr ccm gcm drbg curl sqlite
Running 3 'newhope' test suites:
  Running suite 'newhope_ke':
    Running case 'ke_good': -
      Failure in 'test_newhope_ke_good': i_nh != NULL (suites/test_newhope_ke.c:39, i = 0)
    Running case 'ke_wrong': -
      Failure in 'test_newhope_ke_wrong': i_nh != NULL (suites/test_newhope_ke.c:83, i = 0)
    Running case 'ke_fail_i': -
      Failure in 'test_newhope_ke_fail_i': i_nh != NULL (suites/test_newhope_ke.c:135, i = 0)
    Running case 'ke_fail_r': -
      Failure in 'test_newhope_ke_fail_r': r_nh != NULL (suites/test_newhope_ke.c:162, i = 0)
  Passed 0/4 'newhope_ke' test cases
  Running suite 'newhope_noise':
    Running case 'noise_uniform': +++++
    Running case 'noise_poly': +++++
    Running case 'noise_fail': ++++
  Passed all 3 'newhope_noise' test cases
  Running suite 'newhope_reconciliation':
    Running case 'rec_good': +
  Passed all 1 'newhope_reconciliation' test cases
Passed 2 of 3 'newhope' suites
FAIL: newhope_tests
==================
1 of 1 test failed
==================
```
Please let me know if you need more details.

**Comment by Thermi** [comment] 2022-08-08 00:27
Check test logs, there's some way to get them, I don't quite remember how. But there should be a way to do that. I had similar issues with other tests in the past.

**Comment by strongX509** [comment] 2022-08-08 08:23
There seems to be a problem with your `openssl` plugin
````
plugin 'openssl': failed to load - openssl_plugin_create returned NULL
````
`newhope` regression tests (**Linux latest (all, gcc, no, no)**) for strongSwan 5.9.7 were successful:
````
Running 3 'newhope' test suites:
  Running suite 'newhope_ke':
    Running case 'ke_good': +
    Running case 'ke_wrong': +
    Running case 'ke_fail_i': +
    Running case 'ke_fail_r': +
  Passed all 4 'newhope_ke' test cases
  Running suite 'newhope_noise':
    Running case 'noise_uniform': +++++
    Running case 'noise_poly': +++++
    Running case 'noise_fail': ++++
  Passed all 3 'newhope_noise' test cases
  Running suite 'newhope_reconciliation':
    Running case 'rec_good': +
  Passed all 1 'newhope_reconciliation' test cases
Passed all 3 'newhope' suites
PASS: newhope_tests
````
What version of  the `openssl` library are you using?

**Comment by strongX509** [comment] 2022-08-08 08:59
Hmmm, it seems that you have OpenSSL FIPS enabled
````
unable to load OpenSSL FIPS provider
````
but the FIPS provider doesn't load, see

https://github.com/strongswan/strongswan/blob/master/src/libstrongswan/plugins/openssl/openssl_plugin.c#L824

**Comment by tobiasbrunner** [comment] 2023-05-26 12:32
Closing this as no further information was provided.

**Closed by tobiasbrunner** 2023-05-26 12:32 UTC
Labels: bug, new
