### ISSUE TITLE
Segfault when compile with optimization flags

### ISSUE THREAD

**Issue by Galaxy0419** [strongswan/strongswan#1080] opened 2022-06-04 09:25 UTC
**System (please complete the following information):**
 - OS: Arch Linux
 - Kernel version (if applicable): 5.15.44-1-lts
 - strongSwan version(s): 5.9.6
 - Tested/confirmed with the latest version: yes

**Describe the bug**
Segfault when compile with optimization flags (e.g. -O2).  Does not happen when overriding CFLAGS to -O0

**To Reproduce**
1. run ```charon-systemd```
2. run command ```swanctl --load-all```

**Expected behavior**
The daemon does not crash

**Logs/Backtraces**
gdb backtrace:
```
Thread 13 "charon-systemd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1cb6640 (LWP 657687)]
0x00007ffff74e2391 in _cb_parse_bool (out=out@entry=0x0, v=...) at vici_config.c:856
856			*out = d;
(gdb) bt
#0  0x00007ffff74e2391 in _cb_parse_bool (out=out@entry=0x0, v=...) at vici_config.c:856
#1  0x00007ffff74dcb8b in parse_option (add_if_true=true, v=..., opt=OPT_IPCOMP, out=<optimized out>) at vici_config.c:899
#2  _cb_parse_opt_ipcomp (out=<optimized out>, v=...) at vici_config.c:943
#3  0x00007ffff74de9bb in parse_rules (rules=rules@entry=0x7ffff1cb5040, count=count@entry=38, name=0x7fffc0002a90 "ipcomp", value=..., reply=0x7ffff1cb5a48) at vici_config.c:243
#4  0x00007ffff74df30d in _cb_child_kv (child=child@entry=0x7ffff1cb54c0, message=message@entry=0x7fffc0000e00, name=<optimized out>, value=...) at vici_config.c:1812
#5  0x00007ffff74d49c9 in parse (this=0x7fffc0000e00, ctx=0x7ffff1cb59d0, section=0x0, kv=0x7ffff74ded20 <_cb_child_kv>, li=0x7ffff74df330 <_cb_child_li>, user=0x7ffff1cb54c0)
    at vici_message.c:501
#6  0x00007ffff74dd745 in _cb_children_sn (peer=peer@entry=0x7ffff1cb5870, message=message@entry=0x7fffc0000e00, ctx=ctx@entry=0x7ffff1cb59d0, name=0x7fffc0002590 "nf")
    at vici_config.c:2051
#7  0x00007ffff74d4a7b in parse (this=0x7fffc0000e00, ctx=0x7ffff1cb59d0, section=0x7ffff74dd680 <_cb_children_sn>, kv=0x0, li=0x0, user=0x7ffff1cb5870) at vici_message.c:530
#8  0x00007ffff74d4a7b in parse (this=0x7fffc0000e00, ctx=0x7ffff1cb59d0, section=0x7ffff74e0f80 <_cb_peer_sn>, kv=0x7ffff74df3f0 <_cb_peer_kv>, li=0x7ffff74df7d0 <_cb_peer_li>, 
    user=0x7ffff1cb5870) at vici_message.c:530
#9  0x00007ffff74e00b2 in _cb_config_sn (request=request@entry=0x7ffff1cb5a40, message=message@entry=0x7fffc0000e00, ctx=ctx@entry=0x7ffff1cb59d0, name=0x7fffc0001580 "nf")
    at vici_config.c:2488
#10 0x00007ffff74d4a7b in parse (this=0x7fffc0000e00, ctx=0x7ffff1cb59d0, section=0x7ffff74dff80 <_cb_config_sn>, kv=0x0, li=0x0, user=0x7ffff1cb5a40) at vici_message.c:530
#11 0x00007ffff74dd1ab in _cb_load_conn (this=<optimized out>, name=<optimized out>, id=<optimized out>, message=<optimized out>) at vici_config.c:2703
#12 0x00007ffff74d6185 in process_request (this=this@entry=0x5555555a3570, name=name@entry=0x7ffff1cb5af0 "load-conn", id=id@entry=1, data=...) at vici_dispatcher.c:289
#13 0x00007ffff74d6515 in _cb_inbound (this=0x5555555a3570, id=1, data=...) at vici_dispatcher.c:346
#14 0x00007ffff74d2de9 in _cb_process_queue (sel=0x7fffc0000b70) at vici_socket.c:510
#15 0x00007ffff7f846f2 in execute (this=<optimized out>) at processing/jobs/callback_job.c:77
#16 0x00007ffff7f85056 in process_job (worker=0x5555555aded0, this=0x55555555bb40) at processing/processor.c:262
#17 _cb_process_jobs (worker=0x5555555aded0) at processing/processor.c:185
#18 0x00007ffff7f985ce in thread_main (this=0x5555555adf00) at threading/thread.c:331
#19 0x00007ffff7b6c54d in ?? () from /usr/lib/libc.so.6
#20 0x00007ffff7bf1b14 in clone () from /usr/lib/libc.so.6
(gdb) 
```

**Additional context**
gcc version: 12.1.0

**Comment by tobiasbrunner** [comment] 2022-06-07 07:34
This is a duplicate of #1053.

**Closed by tobiasbrunner** 2022-06-07 07:34 UTC
Labels: bug, duplicate
