### ISSUE TITLE
VPN connection randomly breaks, impossible to reconnect after that

### ISSUE THREAD

**Issue by NicolasEspiau-urbasolar** [strongswan/strongswan#1461] opened 2022-12-14 15:00 UTC
**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Kernel version (if applicable): 5.15.0-56-generic
 - strongSwan version(s): 5.9.5-2ubuntu2.1
 - Tested/confirmed with the latest version: yes

**Describe the bug**
I've deployed an Azure Virtual Gateway, and following the Microsoft documentation I installed strongswan to setup a VPN point2site connection.
I've been able to create the VPN connection and set it up with values and certs provided by Azure and used to create the Gateway.

The bug is: once connected, the VPN connection breaks after what seems to be a totally random amount of time (can be minutes or hours).
By "breaks" I mean the traffic that's supposed to be routed to the gateway is not routed anymore (therefore I can't access my private resources in Azure, such as my AKS cluster), and I have absolutely no error message anywhere.
Ubuntu NetworkManager considers the VPN connection as still active.

When I disconnect it, I'm unable to reconnect it for let's say 6 or 7 minutes with the following error:
```bash
plugin NeedSecrets request #1 failed: Timeout was reached
```

**To Reproduce**
1. Deploy an Azure Virtual Gateway
2. Set it up following documentation [here](https://learn.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-certificates-point-to-site-linux)
3. Create a VPN Connection with NetworkManager UI
4. Work and wait for the bug.

**Expected behavior**
VPN connection should still route traffic, and I should be able to reconnect whenever I want.

**Logs/Backtraces**
```bash
déc. 14 15:46:13 bonjour-laptop NetworkManager[332558]: <info>  [1671029173.6695] vpn[0x563471c068e0,cc7331f3-8109-4e51-bf65-2e60b9252b07,"Urba-Hub"]: starting strongswan
déc. 14 15:46:13 bonjour-laptop NetworkManager[332558]: <info>  [1671029173.6702] audit: op="connection-activate" uuid="cc7331f3-8109-4e51-bf65-2e60b9252b07" name="Urba-Hub" pid=2785 uid=1000 result="success"
déc. 14 15:46:23 bonjour-laptop NetworkManager[332558]: <warn>  [1671029183.6752] vpn[0x563471c068e0,cc7331f3-8109-4e51-bf65-2e60b9252b07,"Urba-Hub"]: plugin NeedSecrets request #1 failed: Timeout was reached
```

**Comment by Thermi** [comment] 2022-12-14 22:26
I suspect the error message is in regards to asking for a PSK. Maybe try storing it in NM or setup the same connection but with swanctl and log to a file and wait for the error to occur

**Comment by NicolasEspiau-urbasolar** [comment] 2022-12-15 14:33
> 

Thanks @Thermi.
The problem is I've never used strongswan before and I don't know how to use swanctl. All I get is `connecting to 'unix:///var/run/charon.vici' failed: No such file or directory` and I don't understand it.

**Comment by tobiasbrunner** [comment] 2022-12-15 14:43
There is no reason to use swanctl to reproduce the connectivity issue. This can be done with the NM plugin just fine (it logs to syslog, logging to a file, see e.g. #196 for recommended settings, can be configured by adding the `filelog` section to a `charon-nm` top-level section in strongswan.conf). Note that `charon-nm` has to be terminated manually so it picks up changed configs, e.g. via `sudo pkill charon-nm`, because NM will keep it running once started.

**Comment by tobiasbrunner** [comment] 2023-05-26 12:46
Closing this as no further information was provided.

**Closed by tobiasbrunner** 2023-05-26 12:46 UTC
Labels: bug
