### ISSUE TITLE
GTK4 support in plugin NetworkManager-strongswan-gnome

### ISSUE THREAD

**Issue by ilgrad** [strongswan/strongswan#984] opened 2022-04-02 19:21 UTC
Fedora 36
NetworkManager-strongswan-gnome-1.5.2-2.fc36.x86_64

in GUI NetworlManager:  "Error: unable to load VPN connection editor"

Check ui in    /usr/share/gnome-vpn-properties/strongswan/nm-strongswan-dialog.ui:
[ilgrad@arz strongswan]$ sudo gtk4-builder-tool simplify --replace --3to4 nm-strongswan-dialog.ui 
nm-strongswan-dialog.ui:8: property GtkBox::border_width not found
nm-strongswan-dialog.ui:81: property GtkFileChooserButton::visible not found
nm-strongswan-dialog.ui:82: property GtkFileChooserButton::can_focus not found
nm-strongswan-dialog.ui:84: property GtkFileChooserButton::hexpand not found
nm-strongswan-dialog.ui:224: property GtkFileChooserButton::visible not found
nm-strongswan-dialog.ui:225: property GtkFileChooserButton::can_focus not found
nm-strongswan-dialog.ui:227: property GtkFileChooserButton::hexpand not found
nm-strongswan-dialog.ui:249: property GtkFileChooserButton::visible not found
nm-strongswan-dialog.ui:250: property GtkFileChooserButton::can_focus not found
nm-strongswan-dialog.ui:252: property GtkFileChooserButton::hexpand not found
nm-strongswan-dialog.ui:385: property GtkBox::border_width not found
nm-strongswan-dialog.ui:586: Packing property GtkNotebook::position not found
nm-strongswan-dialog.ui:496: property GtkBox::border_width not found

run with verbose:
[ilgrad@arz strongswan]$ gnome-control-center --verbose 
[ilgrad@arz strongswan]$ gnome-control-center --verbose 
22:20:27.0956          network-cc-panel:    DEBUG: coldplugging devices
22:20:27.0956          network-cc-panel:    DEBUG: New device added
22:20:27.0956          network-cc-panel:    DEBUG: New device added
22:20:27.0956          network-cc-panel:    DEBUG: device /sys/devices/pci0000:00/0000:00:02.1/0000:03:00.0/net/enp3s0 type 1 path /org/freedesktop/NetworkManager/Devices/2
22:20:27.0957          network-cc-panel:    DEBUG: New device added
22:20:27.0957          network-cc-panel:    DEBUG: device /sys/devices/pci0000:00/0000:00:02.2/0000:04:00.0/net/wlp4s0 type 2 path /org/freedesktop/NetworkManager/Devices/3
22:20:27.0957          network-cc-panel:    DEBUG: New device added
22:20:27.0957          network-cc-panel:    DEBUG: Calling handle_argv() after cold-plugging devices
22:20:27.0960      diagnostics-cc-panel:    DEBUG: ABRT appeared
22:20:30.0792                    (null):  WARNING: Couldn't load builder file: (unknown)
22:20:30.0792              GLib-GObject:  WARNING: invalid (NULL) pointer instance
22:20:30.0792              GLib-GObject: CRITICAL: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

also similar bag: https://gitlab.gnome.org/GNOME/gtk/-/issues/4740

**Comment by tobiasbrunner** [comment] 2022-04-04 07:46
I suppose this is a duplicate of #961.

**Closed by tobiasbrunner** 2022-04-04 07:46 UTC
Labels: bug
